export enum CHECKLIST_BUYSIDE_DOCUMENT {
  ratifiedSalesContract= 'Save/Archive Ratified Sales Contract and PDF Copy of MLS Listing',
  scheduleInspection = 'Schedule inspection, inform Client and List Agent',
  checkMLS = 'Check that MLS was updated to show as Pending',
  sendContractToClosing = 'Send Contract & PDF of the MLS Listing to Closing Attorney/Title Company',
  handleEarnestMoney = 'Handle Earnest Money',
  repairAddendumOrTermination = 'Repair Addendum signed by both parties ~or~ Termination turned in prior to Expiration',
  confirmCL100Termite = 'Confirm Agent on the other side has ordered CL100/Termite Inspection, inform Client',
  checkClosingAttorney = 'Check with Closing Attorney/Title Company for Time of Closing; inform Client',
  requestRepairReceipts = 'Request repair receipts from Listing Agent',
  checkAppraisalStatus = 'Check status of Appraisal',
  sendCommissionInstructions = 'Send Commission wiring instructions or invoice to Attorney/Title Company',
  orderHomeWarranty = 'Order Home Warranty, inform Agent on the other side',
  confirmTRID = 'Confirm Buyer Client has signed TRID from Lender',
  reviewClosingDisclosure = 'Review Closing Disclosure / Alta with Client',
  confirmUtilitiesScheduled = 'Confirm with the Client that Utilities have been scheduled to start',
  getClosingGift = 'Get Closing Gift',
  scheduleFinalWalkthrough = 'Schedule Final Walkthrough, inform Client and Listing Agent',
  confirmLocationOfKeys = 'Confirm location of keys, fobs, garage door openers, pool key, mailbox keys, etc',
  requestReview = 'Request Review from Client',
  confirmMLSClosed = 'Confirm MLS status has been updated to Closed',
  saveClosingDocuments = 'Save/Archive Closing Documents',
  uploadDocumentsToBrokerage = 'Upload necessary documents to Brokerage',
  remindBuyerPropertyTax = 'Remind Buyer to apply for primary resident property tax',
  confirmBuyerPropertyTax = 'Confirm Buyer applied for primary resident property tax',
  checkIn3Months = '3 Month Check-In on Client',
  checkIn6Months = '6 Month Check-In on Client',
  checkIn9Months = '9 Month Check-In on Client',
  anniversaryGift = 'Happy 1 Year Anniversary Gift to Client',
  }
  