export enum CHECKLIST_LISTSIDE_DOCUMENT {
    ratifiedSalesContract= 'Save/Archive Ratified Sales Contract and PDF Copy of MLS Listing',
    inspectionScheduled= 'Inform Client when Inspection is scheduled',
    mlsPropertypending= 'Update MLS to show property as Pending',
    sendToClosing= 'Send Contract & PDF of MLS Listing to Closing Attorney/Title Company',
    confirmReceipt= 'Confirm receipt of Earnest Money',
    repairAddendumOrTermination= 'Repair Addendum signed by both parties ~or~ Termination turned in prior to Expiration',
    orderCL100Termite= 'Order CL100/Termite Inspection, inform Client and Agent on other side',
    checkClosingAttorney= 'Check with Closing Attorney/Title Company for Time of Closing; inform Client',
    provideRepairReceipts= 'Provide repair receipts to Buyer’s Agent',
    requestAppraisalStatus= 'Request status of Appraisal',
    sendCommissionInstructions= 'Send Commission wiring instructions or invoice to Attorney/Title Company',
    checkHomeWarranty= 'Check that Home Warranty was Ordered',
    askBuyerTRID= 'Ask if Buyer has signed TRID from Lender',
    reviewClosingDisclosure= 'Review Closing Disclosure / Alta with Client',
    confirmUtilitiesScheduled= 'Confirm with Client that Utilities have been scheduled for cut-off',
    getClosingGift= 'Get Closing Gift',
    confirmFinalWalkthrough= 'Confirm when Buyer’s Agent has scheduled Final Walkthrough, inform Client',
    shareLocationKeys= 'Share location of keys, fobs, garage door openers, pool key, mailbox keys, etc with Buyer’s Agent',
    requestReview= 'Request Review from Client',
    updateMLSClosed= 'Update MLS status to Closed',
    saveClosingDocuments= 'Save/Archive Closing Documents',
    uploadDocumentsToBrokerage= 'Upload necessary documents to Brokerage',
    remindSellerInsuranceRefund= 'Remind Seller to Request Property Insurance Refund',
    askSellerReceivedInsuranceRefund= 'Ask if Seller Received Property Insurance Refund',
    checkIn3Months= '3 Month Check-In on Client',
    checkIn6Months= '6 Month Check-In on Client',
    checkIn9Months= '9 Month Check-In on Client',
    anniversaryGift= 'Happy 1 Year Anniversary Gift to Client'
  }
  