export enum CHECKLIST_BOTHSIDE_DOCUMENT {
    ratifiedSalesContract= 'Save/Archive Ratified Sales Contract and PDF Copy of MLS Listing',
    scheduleInspection = 'Schedule inspection, inform Client and List Agent',
    mlsPropertypending= 'Update MLS to show property as Pending',
    sendToClosing= 'Send Contract & PDF of MLS Listing to Closing Attorney/Title Company',
    handleEarnestMoney = 'Handle Earnest Money',
    repairAddendumOrTermination= 'Repair Addendum signed by both parties ~or~ Termination turned in prior to Expiration',
    orderCL100Termite= 'Order CL100/Termite Inspection, inform Client and Agent on other side',
    checkClosingAttorney= 'Check with Closing Attorney/Title Company for Time of Closing; inform Client',
    shareRepairReceipts= 'Share repair receipts from List Client to Buyer Client',
    checkAppraisalStatus = 'Check status of Appraisal',
    sendCommissionInstructions= 'Send Commission wiring instructions or invoice to Attorney/Title Company',
    orderHomeWarranty = 'Order Home Warranty',
    confirmTRID = 'Confirm Buyer Client has signed TRID from Lender',
    reviewClosingDisclosure = 'Review Closing Disclosure / Alta with Client',
    confirmUtilitiesScheduled = 'Confirm List Client has scheduled Utilities for cut-off and Buyer has scheduled to start',
    scheduleFinalWalkthrough = 'Schedule Final Walkthrough, between clients',
    getClosingGift = 'Get Closing Gift',
    shareLocationKeys= 'Share location of keys, fobs, garage door openers, pool key, mailbox keys, etc with Buyer’s Agent',
    requestReview= 'Request Review from Client',
    updateMLSClosed= 'Update MLS status to Closed',
    saveClosingDocuments= 'Save/Archive Closing Documents',
    uploadDocumentsToBrokerage= 'Upload necessary documents to Brokerage',
    remindSellerInsuranceRefund= 'Remind Seller to Request Property Insurance Refund, and  Buyer to apply for primary resident property tax',
    askSellerReceivedInsuranceRefund= 'Ask if Seller Received Property Insurance Refund, Confirm Buyer applied for primary resident property tax',
    checkIn3Months= '3 Month Check-In on Clients',
    checkIn6Months= '6 Month Check-In on Clients',
    checkIn9Months= '9 Month Check-In on Clients',
    anniversaryGift= 'Happy 1 Year Anniversary Gift to Client'
  }
  